import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: 'cadastros',
      columns: [
        { name: 'nome', type: 'string' },
        { name: 'cpf', type: 'string' },
        { name: 'rg', type: 'string', isOptional: true },
        { name: 'data_nascimento', type: 'string', isOptional: true },
        { name: 'idade', type: 'number', isOptional: true },
        { name: 'genero', type: 'string', isOptional: true },
        { name: 'estado_civil', type: 'string', isOptional: true },
        { name: 'nacionalidade', type: 'string', isOptional: true },
        { name: 'naturalidade', type: 'string', isOptional: true },
        { name: 'escolaridade', type: 'string', isOptional: true },
        { name: 'profissao', type: 'string', isOptional: true },
        { name: 'telefone', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'endereco', type: 'string', isOptional: true },
        { name: 'bairro', type: 'string', isOptional: true },
        { name: 'municipio', type: 'string', isOptional: true },
        { name: 'cep', type: 'string', isOptional: true },
        { name: 'ponto_referencia', type: 'string', isOptional: true },
        { name: 'gps_lat', type: 'number', isOptional: true },
        { name: 'gps_lng', type: 'number', isOptional: true },
        { name: 'num_pessoas_familia', type: 'number', isOptional: true },
        { name: 'responsavel_familiar', type: 'boolean', isOptional: true },
        { name: 'renda_familiar', type: 'string', isOptional: true },
        { name: 'programa_social', type: 'string', isOptional: true },
        { name: 'tempo_mora_local', type: 'string', isOptional: true },
        { name: 'num_comodos', type: 'number', isOptional: true },
        { name: 'tipo_moradia', type: 'string', isOptional: true },
        { name: 'material_construcao', type: 'string', isOptional: true },
        { name: 'possui_banheiro', type: 'boolean', isOptional: true },
        { name: 'area_risco', type: 'boolean', isOptional: true },
        { name: 'afetado_desastre', type: 'boolean', isOptional: true },
        { name: 'ajuda_defesa_civil', type: 'boolean', isOptional: true },
        { name: 'agua_potavel', type: 'boolean', isOptional: true },
        { name: 'energia_eletrica', type: 'boolean', isOptional: true },
        { name: 'saneamento_basico', type: 'boolean', isOptional: true },
        { name: 'coleta_lixo', type: 'boolean', isOptional: true },
        { name: 'deficiencia', type: 'boolean', isOptional: true },
        { name: 'doenca_cronica', type: 'boolean', isOptional: true },
        { name: 'medicamento_continuo', type: 'boolean', isOptional: true },
        { name: 'documentos_completos', type: 'boolean', isOptional: true },
        { name: 'assistencia_imediata', type: 'boolean', isOptional: true },
        { name: 'prioridade', type: 'string', isOptional: true },
        { name: 'nucleo_familiar', type: 'string', isOptional: true },
        { name: 'observacoes', type: 'string', isOptional: true },
        { name: 'qual_desastre', type: 'string', isOptional: true },
        { name: 'qual_ajuda_defesa_civil', type: 'string', isOptional: true },
        { name: 'qual_deficiencia', type: 'string', isOptional: true },
        { name: 'qual_doenca_cronica', type: 'string', isOptional: true },
        { name: 'qual_medicamento', type: 'string', isOptional: true },
        { name: 'docs_faltantes', type: 'string', isOptional: true },
        { name: 'rascunho', type: 'boolean' },
        { name: 'sincronizado', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'vistorias',
      columns: [
        { name: 'nome_solicitante', type: 'string' },
        { name: 'cpf', type: 'string' },
        { name: 'rg', type: 'string', isOptional: true },
        { name: 'telefone', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'endereco', type: 'string', isOptional: true },
        { name: 'bairro', type: 'string', isOptional: true },
        { name: 'municipio', type: 'string', isOptional: true },
        { name: 'ponto_referencia', type: 'string', isOptional: true },
        { name: 'protocolo', type: 'string', isOptional: true },
        { name: 'gps_lat', type: 'number', isOptional: true },
        { name: 'gps_lng', type: 'number', isOptional: true },
        { name: 'tipificacao', type: 'string', isOptional: true },
        { name: 'nivel_risco', type: 'string', isOptional: true },
        { name: 'localizacao', type: 'string', isOptional: true },
        { name: 'tipo_imovel', type: 'string', isOptional: true },
        { name: 'material_construcao', type: 'string', isOptional: true },
        { name: 'propriedade', type: 'string', isOptional: true },
        { name: 'desabrigados', type: 'number', isOptional: true },
        { name: 'desalojados', type: 'number', isOptional: true },
        { name: 'pessoas_afetadas', type: 'number', isOptional: true },
        { name: 'familias_afetadas', type: 'number', isOptional: true },
        { name: 'danos_materiais', type: 'string', isOptional: true },
        { name: 'endereco_ocorrencia', type: 'string', isOptional: true },
        { name: 'descricao_situacao', type: 'string', isOptional: true },
        { name: 'recomendacoes', type: 'string', isOptional: true },
        { name: 'tipo_estrutura', type: 'string', isOptional: true },
        { name: 'risco_estrutural', type: 'string', isOptional: true },
        { name: 'risco_hidrologico', type: 'string', isOptional: true },
        { name: 'orgao_destino', type: 'string', isOptional: true },
        { name: 'situacao_imovel', type: 'string', isOptional: true },
        { name: 'reavaliacao', type: 'boolean', isOptional: true },
        { name: 'nome_vistoriador', type: 'string', isOptional: true },
        { name: 'matricula', type: 'string', isOptional: true },
        { name: 'fotos', type: 'string', isOptional: true },
        { name: 'rascunho', type: 'boolean' },
        { name: 'sincronizado', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'vistorias_tecnicas',
      columns: [
        { name: 'nome_estabelecimento', type: 'string' },
        { name: 'cnpj', type: 'string', isOptional: true },
        { name: 'nome_responsavel', type: 'string', isOptional: true },
        { name: 'cpf_responsavel', type: 'string', isOptional: true },
        { name: 'telefone', type: 'string', isOptional: true },
        { name: 'endereco', type: 'string', isOptional: true },
        { name: 'bairro', type: 'string', isOptional: true },
        { name: 'gps_lat', type: 'number', isOptional: true },
        { name: 'gps_lng', type: 'number', isOptional: true },
        { name: 'tipo_estabelecimento', type: 'string', isOptional: true },
        { name: 'area_total', type: 'number', isOptional: true },
        { name: 'capacidade_pessoas', type: 'number', isOptional: true },
        { name: 'fotos', type: 'string', isOptional: true },
        { name: 'possui_extintor', type: 'boolean', isOptional: true },
        { name: 'qtd_extintores', type: 'number', isOptional: true },
        { name: 'tipo_extintor', type: 'string', isOptional: true },
        { name: 'extintor_validade', type: 'boolean', isOptional: true },
        { name: 'extintor_localizacao_ok', type: 'boolean', isOptional: true },
        { name: 'sinalizacao_emergencia', type: 'boolean', isOptional: true },
        { name: 'saida_desobstruida', type: 'boolean', isOptional: true },
        { name: 'qtd_saidas', type: 'number', isOptional: true },
        { name: 'rotas_fuga_ok', type: 'boolean', isOptional: true },
        { name: 'instalacao_irregular', type: 'boolean', isOptional: true },
        { name: 'possui_glp', type: 'boolean', isOptional: true },
        { name: 'glp_armazenamento_ok', type: 'boolean', isOptional: true },
        { name: 'sistema_fixo_incendio', type: 'boolean', isOptional: true },
        { name: 'iluminacao_emergencia', type: 'boolean', isOptional: true },
        { name: 'hidrante_reserva', type: 'boolean', isOptional: true },
        { name: 'planta_baixa', type: 'boolean', isOptional: true },
        { name: 'apto_alvara', type: 'boolean', isOptional: true },
        { name: 'necessita_adequacoes', type: 'boolean', isOptional: true },
        { name: 'observacoes', type: 'string', isOptional: true },
        { name: 'descricao_tecnica', type: 'string', isOptional: true },
        { name: 'protocolo', type: 'string', isOptional: true },
        { name: 'orgao_destino', type: 'string', isOptional: true },
        { name: 'situacao_imovel', type: 'string', isOptional: true },
        { name: 'reavaliacao', type: 'boolean', isOptional: true },
        { name: 'matricula', type: 'string', isOptional: true },
        { name: 'rascunho', type: 'boolean' },
        { name: 'sincronizado', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ]
    }),
  ]
});
