import { Model } from '@nozbe/watermelondb';
import { field, date, readonly, text } from '@nozbe/watermelondb/decorators';

export class Cadastro extends Model {
  static table = 'cadastros';

  @text('nome') nome!: string;
  @text('cpf') cpf!: string;
  @text('rg') rg!: string;
  @text('data_nascimento') dataNascimento!: string;
  @field('idade') idade!: number;
  @text('genero') genero!: string;
  @text('estado_civil') estadoCivil!: string;
  @text('nacionalidade') nacionalidade!: string;
  @text('naturalidade') naturalidade!: string;
  @text('escolaridade') escolaridade!: string;
  @text('profissao') profissao!: string;
  @text('telefone') telefone!: string;
  @text('email') email!: string;
  @text('endereco') endereco!: string;
  @text('bairro') bairro!: string;
  @text('municipio') municipio!: string;
  @text('cep') cep!: string;
  @text('ponto_referencia') pontoReferencia!: string;
  @field('gps_lat') gpsLat!: number;
  @field('gps_lng') gpsLng!: number;
  @field('num_pessoas_familia') numPessoasFamilia!: number;
  @field('responsavel_familiar') responsavelFamiliar!: boolean;
  @text('renda_familiar') rendaFamiliar!: string;
  @text('programa_social') programaSocial!: string;
  @text('tempo_mora_local') tempoMoraLocal!: string;
  @field('num_comodos') numComodos!: number;
  @text('tipo_moradia') tipoMoradia!: string;
  @text('material_construcao') materialConstrucao!: string;
  @text('qual_material_construcao') qualMaterialConstrucao!: string;
  @field('possui_banheiro') possuiBanheiro!: boolean;
  @text('obs_banheiro') obsBanheiro!: string;
  @field('area_risco') areaRisco!: boolean;
  @field('afetado_desastre') afetadoDesastre!: boolean;
  @text('qual_desastre') qualDesastre!: string;
  @field('ajuda_defesa_civil') ajudaDefesaCivil!: boolean;
  @text('qual_ajuda_defesa_civil') qualAjudaDefesaCivil!: string;
  @field('agua_potavel') aguaPotavel!: boolean;
  @text('obs_agua_potavel') obsAguaPotavel!: string;
  @field('energia_eletrica') energiaEletrica!: boolean;
  @text('obs_energia_eletrica') obsEnergiaEletrica!: string;
  @field('saneamento_basico') saneamentoBasico!: boolean;
  @text('obs_saneamento_basico') obsSaneamentoBasico!: string;
  @field('coleta_lixo') coletaLixo!: boolean;
  @text('obs_coleta_lixo') obsColetaLixo!: string;
  @field('deficiencia') deficiencia!: boolean;
  @text('qual_deficiencia') qualDeficiencia!: string;
  @field('doenca_cronica') doencaCronica!: boolean;
  @text('qual_doenca_cronica') qualDoencaCronica!: string;
  @field('medicamento_continuo') medicamentoContinuo!: boolean;
  @text('qual_medicamento') qualMedicamento!: string;
  @field('documentos_completos') documentosCompletos!: boolean;
  @text('docs_faltantes') docsFaltantes!: string;
  @field('assistencia_imediata') assistenciaImediata!: boolean;
  @text('prioridade') prioridade!: string;
  @text('observacoes') observacoes!: string;
  @field('rascunho') rascunho!: boolean;
  @field('sincronizado') sincronizado!: boolean;
  @readonly @date('created_at') createdAt!: Date;
  @date('updated_at') updatedAt!: Date;
}
