import { Model } from '@nozbe/watermelondb';
import { field, date, readonly, text } from '@nozbe/watermelondb/decorators';

export class VistoriaTecnica extends Model {
  static table = 'vistorias_tecnicas';

  @text('nome_estabelecimento') nomeEstabelecimento!: string;
  @text('cnpj') cnpj!: string;
  @text('nome_responsavel') nomeResponsavel!: string;
  @text('cpf_responsavel') cpfResponsavel!: string;
  @text('telefone') telefone!: string;
  @text('endereco') endereco!: string;
  @text('bairro') bairro!: string;
  @field('gps_lat') gpsLat!: number;
  @field('gps_lng') gpsLng!: number;
  @text('tipo_estabelecimento') tipoEstabelecimento!: string;
  @field('area_total') areaTotal!: number;
  @field('capacidade_pessoas') capacidadePessoas!: number;
  @text('fotos') fotos!: string;
  @field('possui_extintor') possuiExtintor!: boolean;
  @field('qtd_extintores') qtdExtintores!: number;
  @text('tipo_extintor') tipoExtintor!: string;
  @text('qual_extintor_outro') qualExtintorOutro!: string;
  @field('extintor_validade') extintorValidade!: boolean;
  @field('extintor_localizacao_ok') extintorLocalizacaoOk!: boolean;
  @field('sinalizacao_emergencia') sinalizacaoEmergencia!: boolean;
  @field('saida_desobstruida') saidaDesobstruida!: boolean;
  @field('qtd_saidas') qtdSaidas!: number;
  @field('rotas_fuga_ok') rotasFugaOk!: boolean;
  @field('instalacao_irregular') instalacaoIrregular!: boolean;
  @field('possui_glp') possuiGlp!: boolean;
  @field('glp_armazenamento_ok') glpArmazenamentoOk!: boolean;
  @field('sistema_fixo_incendio') sistemaFixoIncendio!: boolean;
  @text('qual_sistema_fixo') qualSistemaFixo!: string;
  @field('iluminacao_emergencia') iluminacaoEmergencia!: boolean;
  @text('obs_iluminacao') obsIluminacao!: string;
  @field('hidrante_reserva') hidranteReserva!: boolean;
  @text('obs_hidrante') obsHidrante!: string;
  @field('planta_baixa') plantaBaixa!: boolean;
  @text('obs_planta_baixa') obsPlantaBaixa!: string;
  @field('apto_alvara') aptoAlvara!: boolean;
  @field('necessita_adequacoes') necessitaAdequacoes!: boolean;
  @text('observacoes') observacoes!: string;
  @text('descricao_tecnica') descricaoTecnica!: string;
  @text('protocolo') protocolo!: string;
  @text('orgao_destino') orgaoDestino!: string;
  @text('qual_orgao_outro') qualOrgaoOutro!: string;
  @text('situacao_imovel') situacaoImovel!: string;
  @field('reavaliacao') reavaliacao!: boolean;
  @text('nome_vistoriador') nomeVistoriador!: string;
  @text('matricula') matricula!: string;
  @field('rascunho') rascunho!: boolean;
  @field('sincronizado') sincronizado!: boolean;
  @readonly @date('created_at') createdAt!: Date;
  @date('updated_at') updatedAt!: Date;
}
