import { Model } from '@nozbe/watermelondb';
import { field, date, readonly, text } from '@nozbe/watermelondb/decorators';

export class Vistoria extends Model {
  static table = 'vistorias';

  @text('nome_solicitante') nomeSolicitante!: string;
  @text('cpf') cpf!: string;
  @text('rg') rg!: string;
  @text('telefone') telefone!: string;
  @text('email') email!: string;
  @text('endereco') endereco!: string;
  @text('bairro') bairro!: string;
  @text('municipio') municipio!: string;
  @text('ponto_referencia') pontoReferencia!: string;
  @text('protocolo') protocolo!: string;
  @field('gps_lat') gpsLat!: number;
  @field('gps_lng') gpsLng!: number;
  @text('tipificacao') tipificacao!: string;
  @text('qual_tipificacao_outro') qualTipificacaoOutro!: string;
  @text('nivel_risco') nivelRisco!: string;
  @text('localizacao') localizacao!: string;
  @text('tipo_imovel') tipoImovel!: string;
  @text('material_construcao') materialConstrucao!: string;
  @text('qual_material_outro') qualMaterialOutro!: string;
  @text('propriedade') propriedade!: string;
  @field('desabrigados') desabrigados!: number;
  @field('desalojados') desalojados!: number;
  @field('pessoas_afetadas') pessoasAfetadas!: number;
  @field('familias_afetadas') familiasAfetadas!: number;
  @text('danos_materiais') danosMateriais!: string;
  @text('endereco_ocorrencia') enderecoOcorrencia!: string;
  @text('descricao_situacao') descricaoSituacao!: string;
  @text('recomendacoes') recomendacoes!: string;
  @text('tipo_estrutura') tipoEstrutura!: string;
  @text('qual_estrutura_outro') qualEstruturaOutro!: string;
  @text('risco_estrutural') riscoEstrutural!: string;
  @text('obs_risco_estrutural') obsRiscoEstrutural!: string;
  @text('risco_hidrologico') riscoHidrologico!: string;
  @text('obs_risco_hidrologico') obsRiscoHidrologico!: string;
  @text('orgao_destino') orgaoDestino!: string;
  @text('qual_orgao_outro') qualOrgaoOutro!: string;
  @text('situacao_imovel') situacaoImovel!: string;
  @field('reavaliacao') reavaliacao!: boolean;
  @text('nome_vistoriador') nomeVistoriador!: string;
  @text('matricula') matricula!: string;
  @text('fotos') fotos!: string;
  @field('rascunho') rascunho!: boolean;
  @field('sincronizado') sincronizado!: boolean;
  @readonly @date('created_at') createdAt!: Date;
  @date('updated_at') updatedAt!: Date;
}
